<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleSeeder extends Seeder {
    public function run(): void {
        // Get category IDs
        $cats = DB::table('categories')->pluck('id', 'slug');
        $authors = DB::table('authors')->pluck('id', 'name');
        $authorIds = $authors->values()->toArray();

        $now = now();

        $articles = [
            // ── POLITICS ──────────────────────────────────────────
            [
                'title_hi'      => 'संसद का बजट सत्र: वित्त मंत्री ने पेश किया ऐतिहासिक बजट',
                'title_en'      => 'Parliament Budget Session: Finance Minister Presents Historic Budget',
                'slug'          => 'sansad-budget-session-historic',
                'excerpt_hi'    => 'वित्त मंत्री ने आम बजट में मध्यमवर्गीय परिवारों को बड़ी राहत देते हुए आयकर सीमा बढ़ाई।',
                'excerpt_en'    => 'Finance Minister raises income tax exemption limit providing major relief to middle-class families.',
                'content_hi'    => '<p>नई दिल्ली: संसद के बजट सत्र में आज वित्त मंत्री ने ऐतिहासिक बजट पेश किया। इस बजट में मध्यमवर्गीय परिवारों को बड़ी राहत दी गई है। आयकर की सीमा 7 लाख से बढ़ाकर 10 लाख रुपये कर दी गई है।</p><p>कृषि क्षेत्र के लिए 2 लाख करोड़ रुपये का प्रावधान किया गया है। इसके अलावा रेलवे के आधुनिकीकरण के लिए 3.5 लाख करोड़ रुपये आवंटित किए गए हैं।</p><p>शिक्षा और स्वास्थ्य क्षेत्र में भी भारी निवेश का ऐलान किया गया है। नए IIT और AIIMS खोलने की घोषणा भी बजट में की गई है।</p>',
                'content_en'    => '<p>New Delhi: The Finance Minister presented a historic budget in the Parliament Budget Session today. Major relief has been provided to middle-class families with the income tax exemption limit raised from Rs 7 lakh to Rs 10 lakh.</p>',
                'category_id'   => $cats['politics'] ?? 1,
                'author_id'     => $authorIds[0] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80',
                'is_featured'   => 1,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(2),
            ],
            [
                'title_hi'      => 'लोकसभा चुनाव: पाँच राज्यों में मतदान की तारीखें घोषित',
                'title_en'      => 'Lok Sabha Elections: Voting Dates Announced for Five States',
                'slug'          => 'loksabha-election-five-states-dates',
                'excerpt_hi'    => 'चुनाव आयोग ने पाँच राज्यों के विधानसभा चुनावों की तारीखें घोषित कर दी हैं।',
                'excerpt_en'    => 'Election Commission announces assembly election dates for five states.',
                'content_hi'    => '<p>नई दिल्ली: चुनाव आयोग ने आज पाँच राज्यों के विधानसभा चुनावों की तारीखें घोषित कर दीं। इन राज्यों में उत्तर प्रदेश, बिहार, राजस्थान, मध्य प्रदेश और छत्तीसगढ़ शामिल हैं।</p><p>मतदान तीन चरणों में होगा। पहला चरण 15 नवंबर, दूसरा 20 नवंबर और तीसरा 25 नवंबर को होगा। मतगणना 3 दिसंबर को होगी।</p>',
                'content_en'    => '<p>New Delhi: The Election Commission today announced assembly election dates for five states including Uttar Pradesh, Bihar, Rajasthan, Madhya Pradesh and Chhattisgarh.</p>',
                'category_id'   => $cats['politics'] ?? 1,
                'author_id'     => $authorIds[1] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1568991687963-04ea8b5c9d2a?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(5),
            ],

            // ── SPORTS ────────────────────────────────────────────
            [
                'title_hi'      => 'भारत ने इंग्लैंड को 5 विकेट से हराया, सीरीज पर कब्जा',
                'title_en'      => 'India Beat England by 5 Wickets, Clinch Series',
                'slug'          => 'india-beat-england-5-wickets-series',
                'excerpt_hi'    => 'रोहित शर्मा की कप्तानी में भारत ने इंग्लैंड को 5 विकेट से हराकर टी20 सीरीज जीती।',
                'excerpt_en'    => 'Under Rohit Sharma\'s captaincy, India wins T20 series against England by 5 wickets.',
                'content_hi'    => '<p>मुंबई: रोहित शर्मा की अगुआई में भारतीय क्रिकेट टीम ने आज इंग्लैंड को 5 विकेट से हराकर टी20 सीरीज अपने नाम कर ली। विराट कोहली ने 78 रन की नाबाद पारी खेली।</p><p>लक्ष्य का पीछा करते हुए भारत ने 18.3 ओवर में 5 विकेट खोकर मैच जीत लिया। जसप्रीत बुमराह ने 3 विकेट लेकर पहले इंग्लैंड को 165 रन पर रोका था।</p><p>यह सीरीज जीत भारत के लिए ICC रैंकिंग में फायदेमंद साबित होगी।</p>',
                'content_en'    => '<p>Mumbai: The Indian cricket team led by Rohit Sharma won the T20 series against England by 5 wickets. Virat Kohli played an unbeaten innings of 78 runs.</p>',
                'category_id'   => $cats['sports'] ?? 2,
                'author_id'     => $authorIds[2] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1540747913346-19212a4b1b0c?w=800&q=80',
                'is_featured'   => 1,
                'is_breaking'   => 1,
                'published_at'  => $now->copy()->subHours(1),
            ],
            [
                'title_hi'      => 'ओलंपिक 2028: भारत ने 15 खेलों में क्वालिफिकेशन हासिल किया',
                'title_en'      => 'Olympics 2028: India Qualifies in 15 Sports',
                'slug'          => 'olympics-2028-india-qualifies-15-sports',
                'excerpt_hi'    => 'भारतीय खिलाड़ियों ने लॉस एंजेलेस ओलंपिक 2028 के लिए 15 खेलों में क्वालिफिकेशन हासिल की।',
                'excerpt_en'    => 'Indian athletes qualify in 15 sports for Los Angeles Olympics 2028.',
                'content_hi'    => '<p>नई दिल्ली: भारत ने लॉस एंजेलेस ओलंपिक 2028 के लिए 15 विभिन्न खेलों में क्वालिफिकेशन हासिल की है। यह भारत के लिए एक ऐतिहासिक उपलब्धि है।</p><p>भारोत्तोलन, कुश्ती, बॉक्सिंग, शूटिंग और बैडमिंटन में भारतीय खिलाड़ियों ने सबसे अधिक कोटा स्थान हासिल किए हैं।</p>',
                'content_en'    => '<p>New Delhi: India has secured qualification in 15 different sports for the Los Angeles Olympics 2028. This is a historic achievement for India.</p>',
                'category_id'   => $cats['sports'] ?? 2,
                'author_id'     => $authorIds[0] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(8),
            ],

            // ── ENTERTAINMENT ─────────────────────────────────────
            [
                'title_hi'      => 'बॉलीवुड: शाहरुख खान की नई फिल्म का टीजर हुआ वायरल',
                'title_en'      => 'Bollywood: Shah Rukh Khan\'s New Film Teaser Goes Viral',
                'slug'          => 'bollywood-srk-new-film-teaser-viral',
                'excerpt_hi'    => 'शाहरुख खान की अगली फिल्म का टीजर रिलीज होते ही सोशल मीडिया पर वायरल हो गया।',
                'excerpt_en'    => 'Shah Rukh Khan\'s next film teaser goes viral on social media immediately after release.',
                'content_hi'    => '<p>मुंबई: बॉलीवुड के बादशाह शाहरुख खान की अगली बड़ी फिल्म का टीजर रिलीज हो गया है। टीजर रिलीज के कुछ ही घंटों में यह सोशल मीडिया पर ट्रेंड करने लगा।</p><p>फिल्म में शाहरुख खान एक स्पाई एजेंट की भूमिका में नजर आएंगे। फिल्म दिवाली 2026 पर रिलीज होगी। दीपिका पादुकोण इस फिल्म में उनकी हीरोइन होंगी।</p>',
                'content_en'    => '<p>Mumbai: The teaser of Shah Rukh Khan\'s next big film has been released. Within hours of the teaser release, it started trending on social media.</p>',
                'category_id'   => $cats['entertainment'] ?? 3,
                'author_id'     => $authorIds[1] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
                'is_featured'   => 1,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(3),
            ],
            [
                'title_hi'      => 'फिल्म अवार्ड्स: 73वें राष्ट्रीय फिल्म पुरस्कारों की घोषणा',
                'title_en'      => 'Film Awards: 73rd National Film Awards Announced',
                'slug'          => '73rd-national-film-awards-announced',
                'excerpt_hi'    => '73वें राष्ट्रीय फिल्म पुरस्कारों में सर्वश्रेष्ठ फिल्म का खिताब मलयालम फिल्म को मिला।',
                'excerpt_en'    => 'A Malayalam film wins Best Film at the 73rd National Film Awards.',
                'content_hi'    => '<p>नई दिल्ली: सूचना और प्रसारण मंत्रालय ने 73वें राष्ट्रीय फिल्म पुरस्कारों की घोषणा की। इस बार सर्वश्रेष्ठ फिल्म का पुरस्कार एक मलयालम फिल्म को मिला।</p><p>सर्वश्रेष्ठ अभिनेता का पुरस्कार अल्लू अर्जुन को और सर्वश्रेष्ठ अभिनेत्री का पुरस्कार आलिया भट्ट को दिया गया।</p>',
                'content_en'    => '<p>New Delhi: The Ministry of Information and Broadcasting announced the 73rd National Film Awards. The Best Film award went to a Malayalam film this year.</p>',
                'category_id'   => $cats['entertainment'] ?? 3,
                'author_id'     => $authorIds[2] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(12),
            ],

            // ── BUSINESS ──────────────────────────────────────────
            [
                'title_hi'      => 'शेयर बाजार: सेंसेक्स ने पहली बार छुआ 85,000 का स्तर',
                'title_en'      => 'Stock Market: Sensex Touches 85,000 for the First Time',
                'slug'          => 'sensex-touches-85000-first-time',
                'excerpt_hi'    => 'मजबूत विदेशी निवेश और बेहतर आर्थिक आंकड़ों के बीच बॉम्बे स्टॉक एक्सचेंज का सेंसेक्स पहली बार 85,000 के पार पहुँचा।',
                'excerpt_en'    => 'BSE Sensex crosses 85,000 for the first time amid strong FII inflows and positive economic data.',
                'content_hi'    => '<p>मुंबई: भारतीय शेयर बाजार में आज ऐतिहासिक तेजी देखी गई। बॉम्बे स्टॉक एक्सचेंज का सेंसेक्स पहली बार 85,000 के स्तर को पार कर गया।</p><p>विदेशी संस्थागत निवेशकों ने आज 8,500 करोड़ रुपये की खरीदारी की। रिलायंस इंडस्ट्रीज, TCS और इंफोसिस के शेयरों में जबरदस्त तेजी रही।</p><p>विशेषज्ञों का मानना है कि भारतीय अर्थव्यवस्था की मजबूती और वैश्विक बाजारों में सकारात्मक संकेतों के कारण यह उछाल आया।</p>',
                'content_en'    => '<p>Mumbai: Indian stock market witnessed historic rally today. The BSE Sensex crossed the 85,000 level for the first time. FIIs bought shares worth Rs 8,500 crore today.</p>',
                'category_id'   => $cats['business'] ?? 4,
                'author_id'     => $authorIds[0] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
                'is_featured'   => 1,
                'is_breaking'   => 1,
                'published_at'  => $now->copy()->subMinutes(30),
            ],
            [
                'title_hi'      => 'टाटा ग्रुप ने की बड़ी घोषणा, 50,000 नई नौकरियाँ देगा',
                'title_en'      => 'Tata Group Announces 50,000 New Jobs',
                'slug'          => 'tata-group-50000-new-jobs',
                'excerpt_hi'    => 'टाटा ग्रुप ने अगले दो वर्षों में 50,000 नई नौकरियाँ देने की घोषणा की है।',
                'excerpt_en'    => 'Tata Group announces 50,000 new jobs over the next two years.',
                'content_hi'    => '<p>मुंबई: टाटा ग्रुप ने एक बड़ी घोषणा करते हुए कहा कि वह अगले दो वर्षों में 50,000 नई नौकरियाँ देगा। यह नौकरियाँ IT, मैन्युफैक्चरिंग और सर्विस सेक्टर में होंगी।</p><p>टाटा कंसल्टेंसी सर्विसेज, टाटा मोटर्स और टाटा स्टील मिलकर इन नौकरियों की व्यवस्था करेंगे।</p>',
                'content_en'    => '<p>Mumbai: Tata Group announced that it will provide 50,000 new jobs over the next two years in IT, manufacturing and service sectors.</p>',
                'category_id'   => $cats['business'] ?? 4,
                'author_id'     => $authorIds[1] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(6),
            ],

            // ── TECHNOLOGY ────────────────────────────────────────
            [
                'title_hi'      => 'ISRO ने चंद्रयान-4 मिशन की घोषणा की, 2027 में होगा लॉन्च',
                'title_en'      => 'ISRO Announces Chandrayaan-4 Mission, Launch in 2027',
                'slug'          => 'isro-chandrayaan-4-mission-2027',
                'excerpt_hi'    => 'भारतीय अंतरिक्ष अनुसंधान संगठन ने चंद्रयान-4 मिशन की घोषणा की, जो 2027 में चंद्रमा पर लैंड करेगा।',
                'excerpt_en'    => 'ISRO announces Chandrayaan-4 mission which will land on the moon in 2027.',
                'content_hi'    => '<p>बेंगलुरु: भारतीय अंतरिक्ष अनुसंधान संगठन (ISRO) ने आज चंद्रयान-4 मिशन की आधिकारिक घोषणा की। यह मिशन 2027 में चंद्रमा के दक्षिणी ध्रुव पर उतरेगा।</p><p>चंद्रयान-4 में एक लैंडर, रोवर और ऑर्बिटर होगा। इस बार मिशन का मुख्य उद्देश्य चंद्रमा से नमूने लेकर पृथ्वी पर वापस लाना है।</p><p>ISRO अध्यक्ष ने कहा कि यह भारत के अंतरिक्ष कार्यक्रम के इतिहास में सबसे महत्वाकांक्षी मिशन होगा।</p>',
                'content_en'    => '<p>Bengaluru: The Indian Space Research Organisation (ISRO) officially announced the Chandrayaan-4 mission today. The mission will land at the lunar south pole in 2027.</p>',
                'category_id'   => $cats['technology'] ?? 5,
                'author_id'     => $authorIds[2] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1516849677043-ef67c9557e16?w=800&q=80',
                'is_featured'   => 1,
                'is_breaking'   => 1,
                'published_at'  => $now->copy()->subHours(4),
            ],
            [
                'title_hi'      => 'AI क्रांति: भारत में ChatGPT के 5 करोड़ उपयोगकर्ता',
                'title_en'      => 'AI Revolution: ChatGPT Reaches 50 Million Users in India',
                'slug'          => 'ai-revolution-chatgpt-50-million-india',
                'excerpt_hi'    => 'भारत में आर्टिफिशियल इंटेलिजेंस का उपयोग तेजी से बढ़ रहा है, ChatGPT के उपयोगकर्ता 5 करोड़ पहुँचे।',
                'excerpt_en'    => 'AI usage growing rapidly in India as ChatGPT reaches 50 million users.',
                'content_hi'    => '<p>नई दिल्ली: भारत में आर्टिफिशियल इंटेलिजेंस (AI) का उपयोग तेज गति से बढ़ रहा है। OpenAI के ChatGPT के भारत में उपयोगकर्ताओं की संख्या 5 करोड़ को पार कर गई है।</p><p>IT उद्योग के विशेषज्ञों का मानना है कि AI अगले 5 वर्षों में भारत में 10 लाख करोड़ रुपये के व्यापार के अवसर पैदा करेगा।</p>',
                'content_en'    => '<p>New Delhi: AI usage is rapidly growing in India. ChatGPT by OpenAI has crossed 50 million users in India. IT experts believe AI will create business opportunities worth Rs 100 lakh crore in India over the next 5 years.</p>',
                'category_id'   => $cats['technology'] ?? 5,
                'author_id'     => $authorIds[0] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(9),
            ],

            // ── STATE ─────────────────────────────────────────────
            [
                'title_hi'      => 'बिहार में बाढ़: 15 जिले प्रभावित, सेना ने संभाला मोर्चा',
                'title_en'      => 'Bihar Floods: 15 Districts Affected, Army Takes Charge',
                'slug'          => 'bihar-floods-15-districts-army',
                'excerpt_hi'    => 'बिहार में मूसलाधार बारिश के कारण 15 जिलों में बाढ़ की स्थिति बन गई है। सेना बचाव कार्य में जुटी है।',
                'excerpt_en'    => 'Heavy rains cause flood situation in 15 Bihar districts. Army deployed for rescue operations.',
                'content_hi'    => '<p>पटना: बिहार में लगातार बारिश के कारण 15 जिलों में बाढ़ की स्थिति गंभीर हो गई है। गंगा, कोसी और गंडक नदियाँ खतरे के निशान से ऊपर बह रही हैं।</p><p>राज्य सरकार ने सेना से मदद माँगी है और 50 बचाव दल तैनात किए गए हैं। अब तक 2 लाख से अधिक लोगों को सुरक्षित स्थानों पर पहुँचाया गया है।</p>',
                'content_en'    => '<p>Patna: The flood situation has become critical in 15 districts of Bihar due to continuous rains. The Ganga, Kosi and Gandak rivers are flowing above danger marks.</p>',
                'category_id'   => $cats['state'] ?? 6,
                'author_id'     => $authorIds[1] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 1,
                'published_at'  => $now->copy()->subHours(2),
            ],
            [
                'title_hi'      => 'उत्तर प्रदेश: योगी सरकार ने किया 10 नए एक्सप्रेसवे का ऐलान',
                'title_en'      => 'Uttar Pradesh: Yogi Government Announces 10 New Expressways',
                'slug'          => 'uttar-pradesh-10-new-expressways-yogi',
                'excerpt_hi'    => 'उत्तर प्रदेश सरकार ने राज्य में 10 नए एक्सप्रेसवे बनाने की घोषणा की, जिससे 5 लाख रोजगार सृजित होंगे।',
                'excerpt_en'    => 'UP government announces 10 new expressways that will create 5 lakh jobs.',
                'content_hi'    => '<p>लखनऊ: उत्तर प्रदेश के मुख्यमंत्री योगी आदित्यनाथ ने राज्य में 10 नए एक्सप्रेसवे बनाने की घोषणा की है। इन एक्सप्रेसवे के निर्माण से राज्य में 5 लाख नए रोजगार सृजित होंगे।</p><p>यमुना एक्सप्रेसवे के विस्तार के अलावा गोरखपुर-लखनऊ एक्सप्रेसवे के चौड़ीकरण की भी योजना है।</p>',
                'content_en'    => '<p>Lucknow: Uttar Pradesh CM Yogi Adityanath announced 10 new expressways in the state. These will create 5 lakh new jobs in the state.</p>',
                'category_id'   => $cats['state'] ?? 6,
                'author_id'     => $authorIds[2] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(14),
            ],

            // ── WORLD ─────────────────────────────────────────────
            [
                'title_hi'      => 'संयुक्त राष्ट्र: भारत बना सुरक्षा परिषद का स्थायी सदस्य',
                'title_en'      => 'UN Security Council: India Becomes Permanent Member',
                'slug'          => 'un-security-council-india-permanent-member',
                'excerpt_hi'    => 'संयुक्त राष्ट्र सुरक्षा परिषद में सुधार के बाद भारत को स्थायी सदस्यता मिली, यह भारत की बड़ी कूटनीतिक जीत है।',
                'excerpt_en'    => 'India gets permanent membership of UN Security Council after reforms - a major diplomatic victory.',
                'content_hi'    => '<p>न्यूयॉर्क: संयुक्त राष्ट्र सुरक्षा परिषद में ऐतिहासिक सुधार के बाद भारत को स्थायी सदस्यता प्रदान की गई है। यह भारत की बड़ी कूटनीतिक जीत है।</p><p>भारत के साथ ब्राजील, जर्मनी और जापान को भी स्थायी सदस्य बनाया गया है। अब सुरक्षा परिषद में 9 स्थायी सदस्य होंगे।</p>',
                'content_en'    => '<p>New York: India has been granted permanent membership of the UN Security Council after historic reforms. This is a major diplomatic victory for India.</p>',
                'category_id'   => $cats['world'] ?? 7,
                'author_id'     => $authorIds[0] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1526470498-9ae73c665de8?w=800&q=80',
                'is_featured'   => 1,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(7),
            ],
            [
                'title_hi'      => 'रूस-यूक्रेन युद्ध: शांति वार्ता में भारत निभाएगा मध्यस्थ की भूमिका',
                'title_en'      => 'Russia-Ukraine War: India to Play Mediator Role in Peace Talks',
                'slug'          => 'russia-ukraine-india-mediator-peace-talks',
                'excerpt_hi'    => 'रूस और यूक्रेन के बीच शांति वार्ता में भारत मध्यस्थ की भूमिका निभाएगा, दोनों देशों ने भारत पर जताया भरोसा।',
                'excerpt_en'    => 'India to play mediator role in Russia-Ukraine peace talks as both countries express trust in India.',
                'content_hi'    => '<p>नई दिल्ली: रूस-यूक्रेन युद्ध को समाप्त करने के लिए भारत मध्यस्थ की भूमिका निभाने को तैयार है। दोनों देशों ने भारत पर अपना भरोसा जताया है।</p><p>प्रधानमंत्री मोदी ने कहा कि भारत हमेशा शांति का पक्षधर रहा है और वह युद्धविराम के लिए सक्रिय प्रयास करेगा।</p>',
                'content_en'    => '<p>New Delhi: India is ready to play a mediator role to end the Russia-Ukraine war. Both countries have expressed their trust in India. PM Modi said India has always supported peace.</p>',
                'category_id'   => $cats['world'] ?? 7,
                'author_id'     => $authorIds[1] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1549693578-d683be217e58?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(10),
            ],

            // ── HEALTH ────────────────────────────────────────────
            [
                'title_hi'      => 'AIIMS ने विकसित की कैंसर की नई दवाई, 90% सफलता दर',
                'title_en'      => 'AIIMS Develops New Cancer Drug with 90% Success Rate',
                'slug'          => 'aiims-new-cancer-drug-90-percent-success',
                'excerpt_hi'    => 'अखिल भारतीय आयुर्विज्ञान संस्थान के वैज्ञानिकों ने कैंसर की एक नई दवाई विकसित की है जिसकी सफलता दर 90% है।',
                'excerpt_en'    => 'AIIMS scientists develop a new cancer drug with 90% success rate in clinical trials.',
                'content_hi'    => '<p>नई दिल्ली: अखिल भारतीय आयुर्विज्ञान संस्थान (AIIMS) के वैज्ञानिकों ने कैंसर के उपचार में एक बड़ी सफलता हासिल की है। उन्होंने एक ऐसी दवाई विकसित की है जो 90% मामलों में कैंसर को नियंत्रित करने में सफल रही है।</p><p>यह दवाई स्तन कैंसर, फेफड़ों के कैंसर और कोलन कैंसर में विशेष रूप से प्रभावी पाई गई है।</p>',
                'content_en'    => '<p>New Delhi: Scientists at AIIMS have achieved a major breakthrough in cancer treatment. They have developed a drug that has been successful in controlling cancer in 90% of cases.</p>',
                'category_id'   => $cats['health'] ?? 8,
                'author_id'     => $authorIds[2] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80',
                'is_featured'   => 1,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(11),
            ],
            [
                'title_hi'      => 'डेंगू अलर्ट: दिल्ली-NCR में डेंगू के मामले बढ़े, स्वास्थ्य विभाग सतर्क',
                'title_en'      => 'Dengue Alert: Cases Rise in Delhi-NCR, Health Department on Alert',
                'slug'          => 'dengue-alert-delhi-ncr-cases-rise',
                'excerpt_hi'    => 'दिल्ली-NCR में डेंगू के मामलों में अचानक वृद्धि के बाद स्वास्थ्य विभाग ने अलर्ट जारी किया है।',
                'excerpt_en'    => 'Delhi-NCR health department issues alert after sudden spike in dengue cases.',
                'content_hi'    => '<p>नई दिल्ली: दिल्ली-NCR में डेंगू के मामले तेजी से बढ़ रहे हैं। पिछले एक सप्ताह में 500 से अधिक नए मामले दर्ज किए गए हैं।</p><p>स्वास्थ्य विभाग ने लोगों से घरों में पानी जमा न होने देने की अपील की है। विशेष चिकित्सा दल तैनात किए गए हैं।</p>',
                'content_en'    => '<p>New Delhi: Dengue cases are rising rapidly in Delhi-NCR. More than 500 new cases have been recorded in the past week. Health department has appealed to residents not to allow water stagnation.</p>',
                'category_id'   => $cats['health'] ?? 8,
                'author_id'     => $authorIds[0] ?? null,
                'featured_image'=> 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=800&q=80',
                'is_featured'   => 0,
                'is_breaking'   => 0,
                'published_at'  => $now->copy()->subHours(16),
            ],
        ];

        foreach ($articles as $article) {
            DB::table('articles')->insertOrIgnore(array_merge($article, [
                'language'   => 'both',
                'status'     => 'published',
                'views'      => rand(100, 15000),
                'created_at' => $article['published_at'],
                'updated_at' => $article['published_at'],
            ]));
        }
    }
}
